version: '3.9'

services:
  dorientdb1:
    image: orientdb:3.2.42
    ports:
      - 2481:2480
    environment:
      ORIENTDB_NODE_NAME: dorientdb1
      ORIENTDB_ROOT_PASSWORD: "password"
      ORIENTDB_SETTINGS: -Dstorage.diskCache.bufferSize=256
      ORIENTDB_OPTS_MEMORY: -Xmx512m
      HAZELCAST_PLUGIN_STARTUP_DELAY: 2000
    volumes:
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast-1.xml:/orientdb/config/hazelcast.xml
      - ./data/databases/dorientdb1:/orientdb/databases
      - ./data/backup/dorientdb1:/orientdb/backup
    stop_grace_period: 2m
    command: |
      bash -c '
        useradd orientdb --uid 501
        chown -R orientdb /orientdb
        setpriv --reuid=orientdb --regid=orientdb --init-groups --inh-caps=-all dserver.sh debug'

  dorientdb2:
    image: orientdb:3.2.42
    ports:
      - 2482:2480
    environment:
      ORIENTDB_NODE_NAME: dorientdb2
      ORIENTDB_ROOT_PASSWORD: "password"
      ORIENTDB_SETTINGS: -Dstorage.diskCache.bufferSize=256
      ORIENTDB_OPTS_MEMORY: -Xmx512m
      HAZELCAST_PLUGIN_STARTUP_DELAY: 2000
    volumes:
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast-2.xml:/orientdb/config/hazelcast.xml
      - ./data/databases/dorientdb2:/orientdb/databases
      - ./data/backup/dorientdb2:/orientdb/backup
    stop_grace_period: 2m
    command: |
      bash -c '
        useradd orientdb --uid 501
        chown -R orientdb /orientdb
        setpriv --reuid=orientdb --regid=orientdb --init-groups --inh-caps=-all dserver.sh debug'

  dorientdb3:
    image: orientdb:3.2.42
    ports:
      - 2483:2480
    environment:
      ORIENTDB_NODE_NAME: dorientdb3
      ORIENTDB_ROOT_PASSWORD: "password"
      ORIENTDB_SETTINGS: -Dstorage.diskCache.bufferSize=256
      ORIENTDB_OPTS_MEMORY: -Xmx512m
      HAZELCAST_PLUGIN_STARTUP_DELAY: 2000
    volumes:
      - ./config/default-distributed-db-config.json:/orientdb/config/default-distributed-db-config.json
      - ./config/hazelcast-3.xml:/orientdb/config/hazelcast.xml
      - ./data/databases/dorientdb3:/orientdb/databases
      - ./data/backup/dorientdb3:/orientdb/backup
    stop_grace_period: 2m
    command: |
      bash -c '
        useradd orientdb --uid 501
        chown -R orientdb /orientdb
        setpriv --reuid=orientdb --regid=orientdb --init-groups --inh-caps=-all dserver.sh debug'
